### ISSUE TITLE
Conda installation requires boost 1.55.0

### ISSUE THREAD

**Issue by grisaitis** [janelia-flyem/libdvid-cpp#20]
Installation with conda currently requires boost 1.55.0. Is the library compatible with 1.60? If so, could the conda recipe be updated to not require the old boost?

Boost 1.55.0 isn't available in the standard conda channel, so I have to install it from a separate channel e.g. `conda install boost=1.55.0 -c FlyEM`. Ideally I'd like to not have to downgrade.

After dowgrading boost and installing dvid, I tried upgrading boost and seeing if dvid still worked. It didn't. I got an error about the multithreading bit of boost:

```
$ conda install boost=1.60  # upgrade boost
...
$ python code_using_libdvid.py 
Traceback (most recent call last):
...
import libdvid
  File "...../libdvid/__init__.py", line 1, in <module>
    from _dvid_python import *
ImportError: libboost_thread-mt.so.1.55.0: cannot open shared object file: No such file or directory
``` 

Any thoughts on what it would take to make this work with boost 1.60?

**Comment by stuarteberg** [comment]
>Any thoughts on what it would take to make this work with boost 1.60?

I hadn't really considered it before, but getting it working wasn't too hard.  I just uploaded new libdvid packages for mac and linux that link against boost 1.60.0 instead of 1.55.0.

First, make sure you're using the latest version of conda:

```
conda update conda
```

Then try this:

```
conda create -n my-env -c flyem boost=1.60.0 libdvid-cpp
```

**Comment by grisaitis** [comment]
Thanks, I'll try this out! 

Are you aware of any differences between the FlyEM channel's boost and the usual conda channel's boost?

**Comment by stuarteberg** [comment]
I haven't tried the Anaconda version of boost, but it's probably very similar.

If you want to compare, they are probably using this recipe:
https://github.com/conda/conda-recipes/tree/master/boost

Whereas we use this one:
https://github.com/janelia-flyem/flyem-build-conda/tree/master/boost
