### ISSUE TITLE
A bug in get_gray3D()?

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/libdvid-cpp#25]
I tried to fetch grayscale data with the get_gray3D function with throttle=false and compression=true but got my program crashed. The error output is:
DVID Error (400): DVIDException for /node/b6bc/labels/raw/0_1_2/0_1_0/0_0_0?compression=lz4

I could confirm that none of the offset and size parameters is 0.

The default parameters worked fine.

**Comment by stephenplaza** [comment]
It looks like you were trying to call 'labels' with a grayscale get command.  I don't do type checking (which I should) in libdvid.  You probably meant to call 'grayscale' instead which is uint8blk.
