### ISSUE TITLE
conda package conflict

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/libdvid-cpp#33]
libdvid-cpp depends on boost 1.55, which can be a problem if I try to install a package depending on a different version of boost, for example:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - cgal -> boost 1.61.0
  - libdvid-cpp -> boost 1.55.0
Use "conda info <package>" to see the dependencies for each package.
```

Any idea how to get around the problem?

**Comment by stuarteberg** [comment]
Our libdvid-cpp reicpe allows you to build the package with a different version of boost, via a special environment variable:


```
cd libdvid-cpp
BOOST_VER=1.61.0 conda build --python=2.7 --numpy=1.11 conda-recipe
```

...but that may not work in your case, depending on where you got the `cgal` package.  Are you getting it from conda-forge?  If so, then you'll encounter our usual conflict regarding the C++ std library implementation (`stdlibc++` vs `libc++`), assuming you're using Mac.  On Linux, you might not encounter any issues.
