### ISSUE TITLE
numpy version requirement 

### ISSUE THREAD

**Issue by jingpengw** [janelia-flyem/libdvid-cpp#48]
Hi, it seems that the numpy version range is pretty limited. 
This version do not work with python 3.10.
does it really need to use 1.21.6?

```

Encountered problems while solving:
  - package libdvid-cpp-0.4.post21-np121py310_0_gdc080a2 requires numpy >=1.21.6,<1.22.0a0, but no
ne of the providers can be installed
```

I found a related closed issue: https://github.com/janelia-flyem/libdvid-cpp/issues/23

I did not find the place to constrain this version.

**Comment by stuarteberg** [comment]
Okay, I see that conda-forge [doesn't use][1] a `max_pin` for `numpy`, so maybe it's unnecessary.  Instead, recipes seem to use `pin_compatible('numpy')` in their `run` requirements.  I'll try the same.

[1]: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

**Comment by stuarteberg** [comment]
The [latest `libdvid-cpp` package for linux](https://anaconda.org/flyem-forge/libdvid-cpp/0.5.post2/download/linux-64/libdvid-cpp-0.5.post2-np121py310_0_g66f7b8b.tar.bz2) now has a relaxed `numpy` requirement.  (Mac update coming tomorrow.)

```json
    "numpy >=1.21.6,<2.0a0",
```

So maybe that will fix it.

---

```
mamba install -c flyem-forge -c conda-forge 'libdvid-cpp>=0.5.post2'
```

**Comment by jingpengw** [comment]
thank you! I am using it in Mac OS.
I have compiled it locally and it works for now.
