### ISSUE TITLE
Add head command

### ISSUE THREAD

**Issue by csweaver** [janelia-flyem/libdvid-cpp#7]

**Comment by csweaver** [comment]
Can we bump this up in priority? I need it to find 'dead bodies'. Body ids that still exist as annotations but have been merged or split and now have different ids.

**Comment by stephenplaza** [comment]
Before this is implemented, I recommended calling the coarse sparse vol endpoint as a custom call.  Most every call will be under 1 second so you should be able to query dead bodies <1 hr.

**Comment by csweaver** [comment]
That's what I'm doing now, I was afraid it might put too much load on DVID. Bill says DVID supports head calls for sparse volume so this could be added for that.

**Comment by stuarteberg** [comment]
Fixed in #11.  Example python usage:

    connection = DVIDConnection("127.0.0.1:8000")
    http_status_code = connection.make_head_request(uri_endpoint)

BTW, Bill also reimplemented `DVIDNodeService.body_exists()` to use a `HEAD` request.
